[[plugins]]
repo = 'delphinus35/typescript-vim'
rev  = 'colorize-template-strings'
on_ft = ['typescript']

[[plugins]]
repo  = 'Quramy/tsuquyomi'
on_ft = ['typescript']
hook_source = '''
let g:tsuquyomi_completion_detail = 1
'''
