[[plugins]]
repo = 'Shougo/denite.nvim'

[[plugins]]
repo = 'scrooloose/nerdtree'
hook_add = '''
let g:NERDTreeShowHidden=1
nnoremap <silent><C-e> :NERDTreeToggle<CR>
" autocmd bufenter * if (winnr("$") == 1 && exists("b:NERDTree") && b:NERDTree.isTabTree()) | q | endif
'''

[[plugins]]
repo = 'lambdalisue/vim-findent'

[[plugins]]
repo = 'prettier/vim-prettier'
build = 'npm install'
on_ft = ['css', 'less', 'scss', 'json', 'graphql', 'markdown', 'vue', 'yaml', 'html']
hook_add = '''
let g:prettier#autoformat = 0
autocmd BufWritePre *.css,*.less,*.scss,*.json,*.graphql,*.md,*.vue,*.yaml,*.html PrettierAsync
'''

#
# toml
#

[[plugins]]
repo = 'cespare/vim-toml'
on_ft = ['toml']

#
# markdown
#

[[plugins]]
repo = 'plasticboy/vim-markdown'
on_ft = ['markdown']
hook_source = '''
autocmd BufRead,BufNewFile *.mkd  set filetype=markdown
autocmd BufRead,BufNewFile *.md  set filetype=markdown
" Need: kannokanno/previm
nnoremap <silent> <C-p> :PrevimOpen<CR> " Ctrl-pでプレビュー
" 自動で折りたたまないようにする
let g:vim_markdown_folding_disabled=1
'''

[[plugins]]
repo = 'kannokanno/previm'
on_ft = ['markdown']
hook_source = '''
let g:previm_open_cmd = 'open -a Google\ Chrome'
'''

#
# javascript
#

[[plugins]]
repo = 'pangloss/vim-javascript'
on_ft = ['javascript']
hook_source = '''
let g:javascript_plugin_jsdoc = 1
'''

[[plugins]]
repo = 'jelera/vim-javascript-syntax'

#
# typescript
#

[[plugins]]
repo = 'leafgarland/typescript-vim'
on_ft = ['typescript']

[[plugins]]
repo = 'Quramy/tsuquyomi'
on_ft = ['typescript']
hook_source = '''
let g:tsuquyomi_completion_detail = 1
let g:tsuquyomi_shortest_import_path = 1
'''

#
# go
#

[[plugins]]
repo = 'fatih/vim-go'
on_ft = ['go']

[[plugins]]
repo = 'zchee/deoplete-go'
build = 'make'
on_ft = ['go']
hook_source = '''
let g:deoplete#sources#go#gocode_binary = $GOPATH . '/bin/gocode'
let g:deoplete#sources#go#sort_class = ['package', 'func', 'type', 'var', 'const']
'''

#
# sql
#

[[plugins]]
repo = 'vim-scripts/dbext.vim'
on_ft = ['sql']

