[[plugins]]
repo = 'Shougo/dein.vim'

[[plugins]]
repo = 'editorconfig/editorconfig-vim'

# [[plugins]]
# repo = 'Shougo/deoplete.nvim'
# hook_add = '''
# let g:deoplete#enable_at_startup = 1
# autocmd FileType typescript let g:deoplete#disable_auto_complete = 1
#
# inoremap <expr> <C-o> pumvisible() ? "\<C-n>" : "\<Tab>"
# inoremap <expr> <Tab> pumvisible() ? "\<C-n>" : "\<Tab>"
# inoremap <expr> <S-Tab> pumvisible() ? "\<C-p>" : "\<S-Tab>"
# '''

[[plugins]]
repo = 'jacoborus/tender.vim'
hook_add = '''
colorscheme tender
'''

[[plugins]]
repo = 'itchyny/lightline.vim'

# [[plugins]]
# repo = 'w0rp/ale'
# hook_add = '''
# let g:ale_fix_on_save = 1
# let g:ale_completion_enabled = 1
# let g:ale_javascript_prettier_use_local_config = 1
# let g:ale_fixers = {
#       \ 'javascript': ['eslint'],
#       \ 'typescript': ['eslint', 'tslint']
#       \ }
# '''

[[plugins]]
repo = "airblade/vim-gitgutter"

[[plugins]]
repo = "tpope/vim-fugitive"


[[plugins]]
repo = "tpope/vim-commentary"
