[[plugins]]
repo  = 'Quramy/tsuquyomi'
on_ft = 'typescript'

[[plugins]]
repo = 'cespare/vim-toml'
on_ft = 'toml'

[[plugins]]
repo = 'Shougo/deoplete.nvim'
if = 'has("nvim")'
on_i = 1

[[plugins]]
repo = 'artur-shaik/vim-javacomplete2'
on_ft = 'java'
