[[plugins]]
repo = 'Shougo/dein.vim'

[[plugins]]
repo = 'Shougo/vimproc.vim'
build = 'make'

[[plugins]]
repo = 'ConradIrwin/vim-bracketed-paste'

[[plugins]]
repo = 'w0rp/ale'

[[plugins]]
repo = 'editorconfig/editorconfig-vim'

[[plugins]]
repo = 'scrooloose/nerdtree'

[[plugins]]
repo = 'whatyouhide/vim-gotham'


# language plugin
[[plugins]]
repo = 'pangloss/vim-javascript'
on_ft = 'javascript'

[[plugins]]
repo = 'delphinus35/typescript-vim'
rev  = 'colorize-template-strings'
on_ft = 'typescript'

[[plugins]]
repo = 'dart-lang/dart-vim-plugin'
on_ft = 'dart'

[[plugins]]
repo = 'ekalinin/Dockerfile.vim'
build = 'make'

[[plugins]]
repo = 'plasticboy/vim-markdown'
[[plugins]]
repo = 'kannokanno/previm'
[[plugins]]
repo = 'tyru/open-browser.vim'
