[[plugins]]
repo  = 'Quramy/tsuquyomi'
on_ft = 'typescript'

[[plugins]]
repo = 'cespare/vim-toml'
on_ft = 'toml'

[[plugins]]
repo = 'Shougo/deoplete.nvim'

[[plugins]]
repo = 'zchee/deoplete-clang'

[[plugins]]
repo = 'artur-shaik/vim-javacomplete2'
on_ft = 'java'

[[plugins]]
repo = 'zchee/deoplete-go'

[[plugins]]
repo = 'fatih/vim-go'
